# Generated by Django 4.0 on 2022-01-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('whiskies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('country', models.CharField(default='Scotland', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='whiskies.distillery')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
