# Generated by Django 4.0 on 2022-01-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_delete_resume'),
        ('whiskies', '0002_distillery_whisky_delete_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='whiskies.whisky'),
        ),
    ]
