# Generated by Django 4.0 on 2022-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rating_whisky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='nose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='taste',
            field=models.FloatField(),
        ),
    ]
